// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasicComponent: typeof import('./../components/Atomics/BasicComponent.vue')['default']
    BasicLayout: typeof import('./../layout/BasicLayout/index.vue')['default']
    BlankLayout: typeof import('./../layout/BlankLayout/index.vue')['default']
    ColorCheckbox: typeof import('./../layout/components/theme-setting/drawer-content/global-theme/components/ColorCheckbox.vue')['default']
    DrawerButton: typeof import('./../layout/components/theme-setting/drawer-button/index.vue')['default']
    DrawerContent: typeof import('./../layout/components/theme-setting/drawer-content/index.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElRow: typeof import('element-plus/es')['ElRow']
    GlobalConfig: typeof import('./../layout/components/theme-setting/drawer-content/global-config/index.vue')['default']
    GlobalContent: typeof import('./../layout/components/global-content/index.vue')['default']
    GlobalCopy: typeof import('./../layout/components/theme-setting/drawer-content/global-copy/index.vue')['default']
    GlobalFooter: typeof import('./../layout/components/global-footer/index.vue')['default']
    GlobalHeader: typeof import('./../layout/components/global-header/index.vue')['default']
    GlobalLayout: typeof import('./../layout/components/theme-setting/drawer-content/global-layout/index.vue')['default']
    GlobalSider: typeof import('./../layout/components/global-sider/index.vue')['default']
    GlobalTab: typeof import('./../layout/components/global-tab/index.vue')['default']
    GlobalTheme: typeof import('./../layout/components/theme-setting/drawer-content/global-theme/index.vue')['default']
    HeaderCompany: typeof import('./../layout/components/global-header/cpns/header-company.vue')['default']
    HeaderMenu: typeof import('./../layout/components/global-header/cpns/header-menu.vue')['default']
    HomeView: typeof import('./../views/HomeView.vue')['default']
    IconIcOutlineCheck: typeof import('~icons/ic/outline-check')['default']
    LayoutCheckBox: typeof import('./../layout/components/theme-setting/drawer-content/global-layout/components/LayoutCheckBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBurger: typeof import('./../layout/components/global-tab/cpns/tab-burger.vue')['default']
    ThemeSetting: typeof import('./../layout/components/theme-setting/index.vue')['default']
  }
}
